## Append samples of your project ##
resources:
- userauthentication-secret.yaml
- portal.yaml
- userauthentication.yaml
- appauthentication.yaml
- appregistration.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
